# Generated by Django 3.2.4 on 2021-06-12 15:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Realtor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=100)),
                ('photo', models.ImageField(upload_to='photos/realtor/%Y-%m-%d')),
                ('is_mvp', models.BooleanField(default=False)),
                ('hire_date', models.DateField(blank=True, default=datetime.datetime(2021, 6, 12, 21, 5, 31, 754083))),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
    ]
