# Generated by Django 3.2.4 on 2021-06-17 12:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='hire_date',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 6, 17, 17, 54, 15, 353177)),
        ),
    ]
